//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Logistika_snova
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Груз.
    /// </summary>
    // *** Start programmer edit section *** (Груз CustomAttributes)

    // *** End programmer edit section *** (Груз CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ГрузE", new string[] {
            "КодГруза as \'Код груза\'",
            "КатегорияГр as \'Категория груза\'",
            "Ширина as \'Ширина, м\'",
            "Высота as \'Высота, м\'",
            "Длина as \'Длина, м\'",
            "Масса as \'Масса, кг\'",
            "Объем as \'Объем, м^3\'"})]
    [View("ГрузL", new string[] {
            "КодГруза as \'Код груза\'",
            "КатегорияГр as \'Категория груза\'",
            "Ширина as \'Ширина, м\'",
            "Высота as \'Высота, м\'",
            "Длина as \'Длина, м\'",
            "Масса as \'Масса, кг\'",
            "Объем as \'Объем, м^3\'"})]
    public class Груз : ICSSoft.STORMNET.DataObject
    {
        
        private string fКатегорияГр;
        
        private double fШирина;
        
        private double fВысота;
        
        private double fДлина;
        
        private double fМасса;
        
        private double fОбъем;
        
        private int fКодГруза;
        
        // *** Start programmer edit section *** (Груз CustomMembers)

        // *** End programmer edit section *** (Груз CustomMembers)

        
        /// <summary>
        /// Высота.
        /// </summary>
        // *** Start programmer edit section *** (Груз.Высота CustomAttributes)

        // *** End programmer edit section *** (Груз.Высота CustomAttributes)
        public virtual double Высота
        {
            get
            {
                // *** Start programmer edit section *** (Груз.Высота Get start)

                // *** End programmer edit section *** (Груз.Высота Get start)
                double result = this.fВысота;
                // *** Start programmer edit section *** (Груз.Высота Get end)

                // *** End programmer edit section *** (Груз.Высота Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Груз.Высота Set start)

                // *** End programmer edit section *** (Груз.Высота Set start)
                this.fВысота = value;
                // *** Start programmer edit section *** (Груз.Высота Set end)

                // *** End programmer edit section *** (Груз.Высота Set end)
            }
        }
        
        /// <summary>
        /// Длина.
        /// </summary>
        // *** Start programmer edit section *** (Груз.Длина CustomAttributes)

        // *** End programmer edit section *** (Груз.Длина CustomAttributes)
        public virtual double Длина
        {
            get
            {
                // *** Start programmer edit section *** (Груз.Длина Get start)

                // *** End programmer edit section *** (Груз.Длина Get start)
                double result = this.fДлина;
                // *** Start programmer edit section *** (Груз.Длина Get end)

                // *** End programmer edit section *** (Груз.Длина Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Груз.Длина Set start)

                // *** End programmer edit section *** (Груз.Длина Set start)
                this.fДлина = value;
                // *** Start programmer edit section *** (Груз.Длина Set end)

                // *** End programmer edit section *** (Груз.Длина Set end)
            }
        }
        
        /// <summary>
        /// КатегорияГр.
        /// </summary>
        // *** Start programmer edit section *** (Груз.КатегорияГр CustomAttributes)

        // *** End programmer edit section *** (Груз.КатегорияГр CustomAttributes)
        [StrLen(255)]
        public virtual string КатегорияГр
        {
            get
            {
                // *** Start programmer edit section *** (Груз.КатегорияГр Get start)

                // *** End programmer edit section *** (Груз.КатегорияГр Get start)
                string result = this.fКатегорияГр;
                // *** Start programmer edit section *** (Груз.КатегорияГр Get end)

                // *** End programmer edit section *** (Груз.КатегорияГр Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Груз.КатегорияГр Set start)

                // *** End programmer edit section *** (Груз.КатегорияГр Set start)
                this.fКатегорияГр = value;
                // *** Start programmer edit section *** (Груз.КатегорияГр Set end)

                // *** End programmer edit section *** (Груз.КатегорияГр Set end)
            }
        }
        
        /// <summary>
        /// КодГруза.
        /// </summary>
        // *** Start programmer edit section *** (Груз.КодГруза CustomAttributes)

        // *** End programmer edit section *** (Груз.КодГруза CustomAttributes)
        public virtual int КодГруза
        {
            get
            {
                // *** Start programmer edit section *** (Груз.КодГруза Get start)

                // *** End programmer edit section *** (Груз.КодГруза Get start)
                int result = this.fКодГруза;
                // *** Start programmer edit section *** (Груз.КодГруза Get end)

                // *** End programmer edit section *** (Груз.КодГруза Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Груз.КодГруза Set start)

                // *** End programmer edit section *** (Груз.КодГруза Set start)
                this.fКодГруза = value;
                // *** Start programmer edit section *** (Груз.КодГруза Set end)

                // *** End programmer edit section *** (Груз.КодГруза Set end)
            }
        }
        
        /// <summary>
        /// Масса.
        /// </summary>
        // *** Start programmer edit section *** (Груз.Масса CustomAttributes)

        // *** End programmer edit section *** (Груз.Масса CustomAttributes)
        public virtual double Масса
        {
            get
            {
                // *** Start programmer edit section *** (Груз.Масса Get start)

                // *** End programmer edit section *** (Груз.Масса Get start)
                double result = this.fМасса;
                // *** Start programmer edit section *** (Груз.Масса Get end)

                // *** End programmer edit section *** (Груз.Масса Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Груз.Масса Set start)

                // *** End programmer edit section *** (Груз.Масса Set start)
                this.fМасса = value;
                // *** Start programmer edit section *** (Груз.Масса Set end)

                // *** End programmer edit section *** (Груз.Масса Set end)
            }
        }
        
        /// <summary>
        /// Объем.
        /// </summary>
        // *** Start programmer edit section *** (Груз.Объем CustomAttributes)

        // *** End programmer edit section *** (Груз.Объем CustomAttributes)
        public virtual double Объем
        {
            get
            {
                // *** Start programmer edit section *** (Груз.Объем Get start)

                // *** End programmer edit section *** (Груз.Объем Get start)
                double result = this.fОбъем;
                // *** Start programmer edit section *** (Груз.Объем Get end)

                // *** End programmer edit section *** (Груз.Объем Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Груз.Объем Set start)

                // *** End programmer edit section *** (Груз.Объем Set start)
                this.fОбъем = value;
                // *** Start programmer edit section *** (Груз.Объем Set end)

                // *** End programmer edit section *** (Груз.Объем Set end)
            }
        }
        
        /// <summary>
        /// Ширина.
        /// </summary>
        // *** Start programmer edit section *** (Груз.Ширина CustomAttributes)

        // *** End programmer edit section *** (Груз.Ширина CustomAttributes)
        public virtual double Ширина
        {
            get
            {
                // *** Start programmer edit section *** (Груз.Ширина Get start)

                // *** End programmer edit section *** (Груз.Ширина Get start)
                double result = this.fШирина;
                // *** Start programmer edit section *** (Груз.Ширина Get end)

                // *** End programmer edit section *** (Груз.Ширина Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Груз.Ширина Set start)

                // *** End programmer edit section *** (Груз.Ширина Set start)
                this.fШирина = value;
                // *** Start programmer edit section *** (Груз.Ширина Set end)

                // *** End programmer edit section *** (Груз.Ширина Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ГрузE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ГрузE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ГрузE", typeof(IIS.Logistika_snova.Груз));
                }
            }
            
            /// <summary>
            /// "ГрузL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ГрузL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ГрузL", typeof(IIS.Logistika_snova.Груз));
                }
            }
        }
    }
}
