//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Logistika_snova
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Докум постав.
    /// </summary>
    // *** Start programmer edit section *** (ДокумПостав CustomAttributes)

    // *** End programmer edit section *** (ДокумПостав CustomAttributes)
    [AutoAltered()]
    [Caption("Документ поставки")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ДокумПоставE", new string[] {
            "Дата as \'Дата документа поставки\'",
            "НомДокПостав as \'Номер документа поставки\'",
            "Организация as \'Наименование организации\'",
            "Организация.НаимОрганиз as \'Наименование организации\'",
            "Сотрудники as \'Ответственный\'",
            "Сотрудники.ФИОСотруд as \'Ответственный\'",
            "Клиенты as \'Наименование заказчика\'",
            "Клиенты.Заказчик as \'Наименование заказчика\'",
            "Клиенты.АдресПоставки as \'Адрес поставки\'",
            "СрокПоставки as \'Срок поставки\'"}, Hidden=new string[] {
            "Организация.НаимОрганиз",
            "Сотрудники.ФИОСотруд",
            "Клиенты.Заказчик"})]
    [AssociatedDetailViewAttribute("ДокумПоставE", "ТЧИнфОЗак", "ТЧИнфОЗакE", true, "", "Информация о заказе", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("ДокумПоставE", "Организация", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "НаимОрганиз")]
    [MasterViewDefineAttribute("ДокумПоставE", "Сотрудники", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИОСотруд")]
    [MasterViewDefineAttribute("ДокумПоставE", "Клиенты", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Заказчик")]
    [View("ДокумПоставL", new string[] {
            "Дата as \'Дата документа поставки\'",
            "НомДокПостав as \'Номер документа поставки\'",
            "Организация.НаимОрганиз as \'Наименование организации\'",
            "Сотрудники.ФИОСотруд as \'Ответственный\'",
            "Клиенты.Заказчик as \'Наименование заказчика\'",
            "Клиенты.АдресПоставки as \'Адрес поставки\'",
            "СрокПоставки as \'Срок поставки\'"})]
    public class ДокумПостав : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата = System.DateTime.Now;
        
        private int fНомДокПостав;
        
        private System.DateTime fСрокПоставки;
        
        private IIS.Logistika_snova.Сотрудники fСотрудники;
        
        private IIS.Logistika_snova.Организация fОрганизация;
        
        private IIS.Logistika_snova.Клиенты fКлиенты;
        
        private IIS.Logistika_snova.DetailArrayOfТЧИнфОЗак fТЧИнфОЗак;
        
        // *** Start programmer edit section *** (ДокумПостав CustomMembers)

        // *** End programmer edit section *** (ДокумПостав CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (ДокумПостав.Дата CustomAttributes)

        // *** End programmer edit section *** (ДокумПостав.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (ДокумПостав.Дата Get start)

                // *** End programmer edit section *** (ДокумПостав.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (ДокумПостав.Дата Get end)

                // *** End programmer edit section *** (ДокумПостав.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокумПостав.Дата Set start)

                // *** End programmer edit section *** (ДокумПостав.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (ДокумПостав.Дата Set end)

                // *** End programmer edit section *** (ДокумПостав.Дата Set end)
            }
        }
        
        /// <summary>
        /// НомДокПостав.
        /// </summary>
        // *** Start programmer edit section *** (ДокумПостав.НомДокПостав CustomAttributes)

        // *** End programmer edit section *** (ДокумПостав.НомДокПостав CustomAttributes)
        public virtual int НомДокПостав
        {
            get
            {
                // *** Start programmer edit section *** (ДокумПостав.НомДокПостав Get start)

                // *** End programmer edit section *** (ДокумПостав.НомДокПостав Get start)
                int result = this.fНомДокПостав;
                // *** Start programmer edit section *** (ДокумПостав.НомДокПостав Get end)

                // *** End programmer edit section *** (ДокумПостав.НомДокПостав Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокумПостав.НомДокПостав Set start)

                // *** End programmer edit section *** (ДокумПостав.НомДокПостав Set start)
                this.fНомДокПостав = value;
                // *** Start programmer edit section *** (ДокумПостав.НомДокПостав Set end)

                // *** End programmer edit section *** (ДокумПостав.НомДокПостав Set end)
            }
        }
        
        /// <summary>
        /// СрокПоставки.
        /// </summary>
        // *** Start programmer edit section *** (ДокумПостав.СрокПоставки CustomAttributes)

        // *** End programmer edit section *** (ДокумПостав.СрокПоставки CustomAttributes)
        public virtual System.DateTime СрокПоставки
        {
            get
            {
                // *** Start programmer edit section *** (ДокумПостав.СрокПоставки Get start)

                // *** End programmer edit section *** (ДокумПостав.СрокПоставки Get start)
                System.DateTime result = this.fСрокПоставки;
                // *** Start programmer edit section *** (ДокумПостав.СрокПоставки Get end)

                // *** End programmer edit section *** (ДокумПостав.СрокПоставки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокумПостав.СрокПоставки Set start)

                // *** End programmer edit section *** (ДокумПостав.СрокПоставки Set start)
                this.fСрокПоставки = value;
                // *** Start programmer edit section *** (ДокумПостав.СрокПоставки Set end)

                // *** End programmer edit section *** (ДокумПостав.СрокПоставки Set end)
            }
        }
        
        /// <summary>
        /// Докум постав.
        /// </summary>
        // *** Start programmer edit section *** (ДокумПостав.Клиенты CustomAttributes)

        // *** End programmer edit section *** (ДокумПостав.Клиенты CustomAttributes)
        [PropertyStorage(new string[] {
                "Клиенты"})]
        [NotNull()]
        public virtual IIS.Logistika_snova.Клиенты Клиенты
        {
            get
            {
                // *** Start programmer edit section *** (ДокумПостав.Клиенты Get start)

                // *** End programmer edit section *** (ДокумПостав.Клиенты Get start)
                IIS.Logistika_snova.Клиенты result = this.fКлиенты;
                // *** Start programmer edit section *** (ДокумПостав.Клиенты Get end)

                // *** End programmer edit section *** (ДокумПостав.Клиенты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокумПостав.Клиенты Set start)

                // *** End programmer edit section *** (ДокумПостав.Клиенты Set start)
                this.fКлиенты = value;
                // *** Start programmer edit section *** (ДокумПостав.Клиенты Set end)

                // *** End programmer edit section *** (ДокумПостав.Клиенты Set end)
            }
        }
        
        /// <summary>
        /// Докум постав.
        /// </summary>
        // *** Start programmer edit section *** (ДокумПостав.Организация CustomAttributes)

        // *** End programmer edit section *** (ДокумПостав.Организация CustomAttributes)
        [PropertyStorage(new string[] {
                "Организация"})]
        [NotNull()]
        public virtual IIS.Logistika_snova.Организация Организация
        {
            get
            {
                // *** Start programmer edit section *** (ДокумПостав.Организация Get start)

                // *** End programmer edit section *** (ДокумПостав.Организация Get start)
                IIS.Logistika_snova.Организация result = this.fОрганизация;
                // *** Start programmer edit section *** (ДокумПостав.Организация Get end)

                // *** End programmer edit section *** (ДокумПостав.Организация Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокумПостав.Организация Set start)

                // *** End programmer edit section *** (ДокумПостав.Организация Set start)
                this.fОрганизация = value;
                // *** Start programmer edit section *** (ДокумПостав.Организация Set end)

                // *** End programmer edit section *** (ДокумПостав.Организация Set end)
            }
        }
        
        /// <summary>
        /// Докум постав.
        /// </summary>
        // *** Start programmer edit section *** (ДокумПостав.Сотрудники CustomAttributes)

        // *** End programmer edit section *** (ДокумПостав.Сотрудники CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудники"})]
        [NotNull()]
        public virtual IIS.Logistika_snova.Сотрудники Сотрудники
        {
            get
            {
                // *** Start programmer edit section *** (ДокумПостав.Сотрудники Get start)

                // *** End programmer edit section *** (ДокумПостав.Сотрудники Get start)
                IIS.Logistika_snova.Сотрудники result = this.fСотрудники;
                // *** Start programmer edit section *** (ДокумПостав.Сотрудники Get end)

                // *** End programmer edit section *** (ДокумПостав.Сотрудники Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокумПостав.Сотрудники Set start)

                // *** End programmer edit section *** (ДокумПостав.Сотрудники Set start)
                this.fСотрудники = value;
                // *** Start programmer edit section *** (ДокумПостав.Сотрудники Set end)

                // *** End programmer edit section *** (ДокумПостав.Сотрудники Set end)
            }
        }
        
        /// <summary>
        /// Докум постав.
        /// </summary>
        // *** Start programmer edit section *** (ДокумПостав.ТЧИнфОЗак CustomAttributes)

        // *** End programmer edit section *** (ДокумПостав.ТЧИнфОЗак CustomAttributes)
        public virtual IIS.Logistika_snova.DetailArrayOfТЧИнфОЗак ТЧИнфОЗак
        {
            get
            {
                // *** Start programmer edit section *** (ДокумПостав.ТЧИнфОЗак Get start)

                // *** End programmer edit section *** (ДокумПостав.ТЧИнфОЗак Get start)
                if ((this.fТЧИнфОЗак == null))
                {
                    this.fТЧИнфОЗак = new IIS.Logistika_snova.DetailArrayOfТЧИнфОЗак(this);
                }
                IIS.Logistika_snova.DetailArrayOfТЧИнфОЗак result = this.fТЧИнфОЗак;
                // *** Start programmer edit section *** (ДокумПостав.ТЧИнфОЗак Get end)

                // *** End programmer edit section *** (ДокумПостав.ТЧИнфОЗак Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокумПостав.ТЧИнфОЗак Set start)

                // *** End programmer edit section *** (ДокумПостав.ТЧИнфОЗак Set start)
                this.fТЧИнфОЗак = value;
                // *** Start programmer edit section *** (ДокумПостав.ТЧИнфОЗак Set end)

                // *** End programmer edit section *** (ДокумПостав.ТЧИнфОЗак Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ДокумПоставE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДокумПоставE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДокумПоставE", typeof(IIS.Logistika_snova.ДокумПостав));
                }
            }
            
            /// <summary>
            /// "ДокумПоставL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДокумПоставL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДокумПоставL", typeof(IIS.Logistika_snova.ДокумПостав));
                }
            }
        }
    }
}
