//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Logistika_snova
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Загрузка баржи.
    /// </summary>
    // *** Start programmer edit section *** (ЗагрузкаБаржи CustomAttributes)

    // *** End programmer edit section *** (ЗагрузкаБаржи CustomAttributes)
    [AutoAltered()]
    [Caption("Загрузка баржи")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗагрузкаБаржиE", new string[] {
            "Дата as \'Дата загрузки баржи\'",
            "НомерДокЗБ as \'Номер документа загрузки баржи\'",
            "Сотрудники as \'Ответственный\'",
            "Сотрудники.ФИОСотруд as \'Ответственный\'",
            "Баржи as \'Номер баржи\'",
            "Баржи.НомерБаржи as \'Номер баржи\'",
            "Баржи.ОбъемБаржи as \'Объем баржи\'",
            "ОбъемБарСв as \'Свободный объем баржи\'",
            "Баржи.Грузопод as \'Грузоподъемность баржи\'",
            "ОстатокПоВесу as \'Остаток по весу баржи\'"}, Hidden=new string[] {
            "Сотрудники.ФИОСотруд",
            "Баржи.НомерБаржи"})]
    [AssociatedDetailViewAttribute("ЗагрузкаБаржиE", "ТЧИнфОКонт", "ТЧИнфОКонтE", true, "", "Информация о погруженных контейнерах", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("ЗагрузкаБаржиE", "Сотрудники", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИОСотруд")]
    [MasterViewDefineAttribute("ЗагрузкаБаржиE", "Баржи", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "НомерБаржи")]
    [View("ЗагрузкаБаржиL", new string[] {
            "Дата as \'Дата загрузки баржи\'",
            "НомерДокЗБ as \'Номер документа загрузки баржи\'",
            "Сотрудники.ФИОСотруд as \'Ответственный\'",
            "Баржи.НомерБаржи as \'Номер баржи\'",
            "Баржи.ОбъемБаржи as \'Объем баржи, м^3\'",
            "ОбъемБарСв as \'Свободный объем баржи, м^3\'",
            "Баржи.Грузопод as \'Грузоподбъемность баржи, тонн\'",
            "ОстатокПоВесу as \'Остаток по весу баржи, тонн\'"})]
    public class ЗагрузкаБаржи : ICSSoft.STORMNET.DataObject
    {
        
        private double fОбъемБарСв;
        
        private double fОстатокПоВесу;
        
        private System.DateTime fДата = System.DateTime.Now;
        
        private int fНомерДокЗБ;
        
        private IIS.Logistika_snova.Баржи fБаржи;
        
        private IIS.Logistika_snova.Сотрудники fСотрудники;
        
        private IIS.Logistika_snova.DetailArrayOfТЧИнфОКонт fТЧИнфОКонт;
        
        // *** Start programmer edit section *** (ЗагрузкаБаржи CustomMembers)

        // *** End programmer edit section *** (ЗагрузкаБаржи CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (ЗагрузкаБаржи.Дата CustomAttributes)

        // *** End programmer edit section *** (ЗагрузкаБаржи.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (ЗагрузкаБаржи.Дата Get start)

                // *** End programmer edit section *** (ЗагрузкаБаржи.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (ЗагрузкаБаржи.Дата Get end)

                // *** End programmer edit section *** (ЗагрузкаБаржи.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗагрузкаБаржи.Дата Set start)

                // *** End programmer edit section *** (ЗагрузкаБаржи.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (ЗагрузкаБаржи.Дата Set end)

                // *** End programmer edit section *** (ЗагрузкаБаржи.Дата Set end)
            }
        }
        
        /// <summary>
        /// НомерДокЗБ.
        /// </summary>
        // *** Start programmer edit section *** (ЗагрузкаБаржи.НомерДокЗБ CustomAttributes)

        // *** End programmer edit section *** (ЗагрузкаБаржи.НомерДокЗБ CustomAttributes)
        public virtual int НомерДокЗБ
        {
            get
            {
                // *** Start programmer edit section *** (ЗагрузкаБаржи.НомерДокЗБ Get start)

                // *** End programmer edit section *** (ЗагрузкаБаржи.НомерДокЗБ Get start)
                int result = this.fНомерДокЗБ;
                // *** Start programmer edit section *** (ЗагрузкаБаржи.НомерДокЗБ Get end)

                // *** End programmer edit section *** (ЗагрузкаБаржи.НомерДокЗБ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗагрузкаБаржи.НомерДокЗБ Set start)

                // *** End programmer edit section *** (ЗагрузкаБаржи.НомерДокЗБ Set start)
                this.fНомерДокЗБ = value;
                // *** Start programmer edit section *** (ЗагрузкаБаржи.НомерДокЗБ Set end)

                // *** End programmer edit section *** (ЗагрузкаБаржи.НомерДокЗБ Set end)
            }
        }
        
        /// <summary>
        /// ОбъемБарСв.
        /// </summary>
        // *** Start programmer edit section *** (ЗагрузкаБаржи.ОбъемБарСв CustomAttributes)

        // *** End programmer edit section *** (ЗагрузкаБаржи.ОбъемБарСв CustomAttributes)
        public virtual double ОбъемБарСв
        {
            get
            {
                // *** Start programmer edit section *** (ЗагрузкаБаржи.ОбъемБарСв Get start)

                // *** End programmer edit section *** (ЗагрузкаБаржи.ОбъемБарСв Get start)
                double result = this.fОбъемБарСв;
                // *** Start programmer edit section *** (ЗагрузкаБаржи.ОбъемБарСв Get end)

                // *** End programmer edit section *** (ЗагрузкаБаржи.ОбъемБарСв Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗагрузкаБаржи.ОбъемБарСв Set start)

                // *** End programmer edit section *** (ЗагрузкаБаржи.ОбъемБарСв Set start)
                this.fОбъемБарСв = value;
                // *** Start programmer edit section *** (ЗагрузкаБаржи.ОбъемБарСв Set end)

                // *** End programmer edit section *** (ЗагрузкаБаржи.ОбъемБарСв Set end)
            }
        }
        
        /// <summary>
        /// ОстатокПоВесу.
        /// </summary>
        // *** Start programmer edit section *** (ЗагрузкаБаржи.ОстатокПоВесу CustomAttributes)

        // *** End programmer edit section *** (ЗагрузкаБаржи.ОстатокПоВесу CustomAttributes)
        public virtual double ОстатокПоВесу
        {
            get
            {
                // *** Start programmer edit section *** (ЗагрузкаБаржи.ОстатокПоВесу Get start)

                // *** End programmer edit section *** (ЗагрузкаБаржи.ОстатокПоВесу Get start)
                double result = this.fОстатокПоВесу;
                // *** Start programmer edit section *** (ЗагрузкаБаржи.ОстатокПоВесу Get end)

                // *** End programmer edit section *** (ЗагрузкаБаржи.ОстатокПоВесу Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗагрузкаБаржи.ОстатокПоВесу Set start)

                // *** End programmer edit section *** (ЗагрузкаБаржи.ОстатокПоВесу Set start)
                this.fОстатокПоВесу = value;
                // *** Start programmer edit section *** (ЗагрузкаБаржи.ОстатокПоВесу Set end)

                // *** End programmer edit section *** (ЗагрузкаБаржи.ОстатокПоВесу Set end)
            }
        }
        
        /// <summary>
        /// Загрузка баржи.
        /// </summary>
        // *** Start programmer edit section *** (ЗагрузкаБаржи.Баржи CustomAttributes)

        // *** End programmer edit section *** (ЗагрузкаБаржи.Баржи CustomAttributes)
        [PropertyStorage(new string[] {
                "Баржи"})]
        [NotNull()]
        public virtual IIS.Logistika_snova.Баржи Баржи
        {
            get
            {
                // *** Start programmer edit section *** (ЗагрузкаБаржи.Баржи Get start)

                // *** End programmer edit section *** (ЗагрузкаБаржи.Баржи Get start)
                IIS.Logistika_snova.Баржи result = this.fБаржи;
                // *** Start programmer edit section *** (ЗагрузкаБаржи.Баржи Get end)

                // *** End programmer edit section *** (ЗагрузкаБаржи.Баржи Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗагрузкаБаржи.Баржи Set start)

                // *** End programmer edit section *** (ЗагрузкаБаржи.Баржи Set start)
                this.fБаржи = value;
                // *** Start programmer edit section *** (ЗагрузкаБаржи.Баржи Set end)

                // *** End programmer edit section *** (ЗагрузкаБаржи.Баржи Set end)
            }
        }
        
        /// <summary>
        /// Загрузка баржи.
        /// </summary>
        // *** Start programmer edit section *** (ЗагрузкаБаржи.Сотрудники CustomAttributes)

        // *** End programmer edit section *** (ЗагрузкаБаржи.Сотрудники CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудники"})]
        [NotNull()]
        public virtual IIS.Logistika_snova.Сотрудники Сотрудники
        {
            get
            {
                // *** Start programmer edit section *** (ЗагрузкаБаржи.Сотрудники Get start)

                // *** End programmer edit section *** (ЗагрузкаБаржи.Сотрудники Get start)
                IIS.Logistika_snova.Сотрудники result = this.fСотрудники;
                // *** Start programmer edit section *** (ЗагрузкаБаржи.Сотрудники Get end)

                // *** End programmer edit section *** (ЗагрузкаБаржи.Сотрудники Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗагрузкаБаржи.Сотрудники Set start)

                // *** End programmer edit section *** (ЗагрузкаБаржи.Сотрудники Set start)
                this.fСотрудники = value;
                // *** Start programmer edit section *** (ЗагрузкаБаржи.Сотрудники Set end)

                // *** End programmer edit section *** (ЗагрузкаБаржи.Сотрудники Set end)
            }
        }
        
        /// <summary>
        /// Загрузка баржи.
        /// </summary>
        // *** Start programmer edit section *** (ЗагрузкаБаржи.ТЧИнфОКонт CustomAttributes)

        // *** End programmer edit section *** (ЗагрузкаБаржи.ТЧИнфОКонт CustomAttributes)
        public virtual IIS.Logistika_snova.DetailArrayOfТЧИнфОКонт ТЧИнфОКонт
        {
            get
            {
                // *** Start programmer edit section *** (ЗагрузкаБаржи.ТЧИнфОКонт Get start)

                // *** End programmer edit section *** (ЗагрузкаБаржи.ТЧИнфОКонт Get start)
                if ((this.fТЧИнфОКонт == null))
                {
                    this.fТЧИнфОКонт = new IIS.Logistika_snova.DetailArrayOfТЧИнфОКонт(this);
                }
                IIS.Logistika_snova.DetailArrayOfТЧИнфОКонт result = this.fТЧИнфОКонт;
                // *** Start programmer edit section *** (ЗагрузкаБаржи.ТЧИнфОКонт Get end)

                // *** End programmer edit section *** (ЗагрузкаБаржи.ТЧИнфОКонт Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗагрузкаБаржи.ТЧИнфОКонт Set start)

                // *** End programmer edit section *** (ЗагрузкаБаржи.ТЧИнфОКонт Set start)
                this.fТЧИнфОКонт = value;
                // *** Start programmer edit section *** (ЗагрузкаБаржи.ТЧИнфОКонт Set end)

                // *** End programmer edit section *** (ЗагрузкаБаржи.ТЧИнфОКонт Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗагрузкаБаржиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗагрузкаБаржиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗагрузкаБаржиE", typeof(IIS.Logistika_snova.ЗагрузкаБаржи));
                }
            }
            
            /// <summary>
            /// "ЗагрузкаБаржиL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗагрузкаБаржиL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗагрузкаБаржиL", typeof(IIS.Logistika_snova.ЗагрузкаБаржи));
                }
            }
        }
    }
}
