//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Logistika_snova
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Т ч расписание.
    /// </summary>
    // *** Start programmer edit section *** (ТЧРасписание CustomAttributes)

    // *** End programmer edit section *** (ТЧРасписание CustomAttributes)
    [AutoAltered()]
    [Caption("Расписание барж")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТЧРасписаниеE", new string[] {
            "ДатаПрибыт as \'Дата прибытия баржи\'",
            "ПунктПриб as \'Пункт прибытия баржи\'"})]
    public class ТЧРасписание : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДатаПрибыт;
        
        private string fПунктПриб;
        
        private IIS.Logistika_snova.Баржи fБаржи;
        
        // *** Start programmer edit section *** (ТЧРасписание CustomMembers)

        // *** End programmer edit section *** (ТЧРасписание CustomMembers)

        
        /// <summary>
        /// ДатаПрибыт.
        /// </summary>
        // *** Start programmer edit section *** (ТЧРасписание.ДатаПрибыт CustomAttributes)

        // *** End programmer edit section *** (ТЧРасписание.ДатаПрибыт CustomAttributes)
        public virtual System.DateTime ДатаПрибыт
        {
            get
            {
                // *** Start programmer edit section *** (ТЧРасписание.ДатаПрибыт Get start)

                // *** End programmer edit section *** (ТЧРасписание.ДатаПрибыт Get start)
                System.DateTime result = this.fДатаПрибыт;
                // *** Start programmer edit section *** (ТЧРасписание.ДатаПрибыт Get end)

                // *** End programmer edit section *** (ТЧРасписание.ДатаПрибыт Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧРасписание.ДатаПрибыт Set start)

                // *** End programmer edit section *** (ТЧРасписание.ДатаПрибыт Set start)
                this.fДатаПрибыт = value;
                // *** Start programmer edit section *** (ТЧРасписание.ДатаПрибыт Set end)

                // *** End programmer edit section *** (ТЧРасписание.ДатаПрибыт Set end)
            }
        }
        
        /// <summary>
        /// ПунктПриб.
        /// </summary>
        // *** Start programmer edit section *** (ТЧРасписание.ПунктПриб CustomAttributes)

        // *** End programmer edit section *** (ТЧРасписание.ПунктПриб CustomAttributes)
        [StrLen(255)]
        public virtual string ПунктПриб
        {
            get
            {
                // *** Start programmer edit section *** (ТЧРасписание.ПунктПриб Get start)

                // *** End programmer edit section *** (ТЧРасписание.ПунктПриб Get start)
                string result = this.fПунктПриб;
                // *** Start programmer edit section *** (ТЧРасписание.ПунктПриб Get end)

                // *** End programmer edit section *** (ТЧРасписание.ПунктПриб Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧРасписание.ПунктПриб Set start)

                // *** End programmer edit section *** (ТЧРасписание.ПунктПриб Set start)
                this.fПунктПриб = value;
                // *** Start programmer edit section *** (ТЧРасписание.ПунктПриб Set end)

                // *** End programmer edit section *** (ТЧРасписание.ПунктПриб Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Logistika_snova.Баржи.
        /// </summary>
        // *** Start programmer edit section *** (ТЧРасписание.Баржи CustomAttributes)

        // *** End programmer edit section *** (ТЧРасписание.Баржи CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Баржи"})]
        public virtual IIS.Logistika_snova.Баржи Баржи
        {
            get
            {
                // *** Start programmer edit section *** (ТЧРасписание.Баржи Get start)

                // *** End programmer edit section *** (ТЧРасписание.Баржи Get start)
                IIS.Logistika_snova.Баржи result = this.fБаржи;
                // *** Start programmer edit section *** (ТЧРасписание.Баржи Get end)

                // *** End programmer edit section *** (ТЧРасписание.Баржи Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧРасписание.Баржи Set start)

                // *** End programmer edit section *** (ТЧРасписание.Баржи Set start)
                this.fБаржи = value;
                // *** Start programmer edit section *** (ТЧРасписание.Баржи Set end)

                // *** End programmer edit section *** (ТЧРасписание.Баржи Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТЧРасписаниеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТЧРасписаниеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТЧРасписаниеE", typeof(IIS.Logistika_snova.ТЧРасписание));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ТЧРасписание.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfТЧРасписание CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfТЧРасписание CustomAttributes)
    public class DetailArrayOfТЧРасписание : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Logistika_snova.DetailArrayOfТЧРасписание members)

        // *** End programmer edit section *** (IIS.Logistika_snova.DetailArrayOfТЧРасписание members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ТЧРасписание by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ТЧРасписание.
        /// </summary>
        public DetailArrayOfТЧРасписание(IIS.Logistika_snova.Баржи fБаржи) : 
                base(typeof(ТЧРасписание), ((ICSSoft.STORMNET.DataObject)(fБаржи)))
        {
        }
        
        public IIS.Logistika_snova.ТЧРасписание this[int index]
        {
            get
            {
                return ((IIS.Logistika_snova.ТЧРасписание)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Logistika_snova.ТЧРасписание dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
