//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Logistika_snova
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Т ч дост кон.
    /// </summary>
    // *** Start programmer edit section *** (ТЧДостКон CustomAttributes)

    // *** End programmer edit section *** (ТЧДостКон CustomAttributes)
    [AutoAltered()]
    [Caption("Доставка контейнеров")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТЧДостКонE", new string[] {
            "ЗагрузКонтейн as \'Номер документа загрузки контейнеров\'",
            "ЗагрузКонтейн.НомерДокЗагк as \'Номер документа загрузки контейнеров\'",
            "Груз as \'Код груза\'",
            "Груз.КодГруза as \'Код груза\'",
            "Груз.КатегорияГр as \'Категория поставленного груза \'",
            "Груз.Объем as \'Объем поставленного груза\'"}, Hidden=new string[] {
            "ЗагрузКонтейн.НомерДокЗагк",
            "Груз.КодГруза"})]
    [MasterViewDefineAttribute("ТЧДостКонE", "ЗагрузКонтейн", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "НомерДокЗагк")]
    [MasterViewDefineAttribute("ТЧДостКонE", "Груз", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "КодГруза")]
    public class ТЧДостКон : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.Logistika_snova.Груз fГруз;
        
        private IIS.Logistika_snova.ЗагрузКонтейн fЗагрузКонтейн;
        
        private IIS.Logistika_snova.ДокумРезультП fДокумРезультП;
        
        // *** Start programmer edit section *** (ТЧДостКон CustomMembers)

        // *** End programmer edit section *** (ТЧДостКон CustomMembers)

        
        /// <summary>
        /// Т ч дост кон.
        /// </summary>
        // *** Start programmer edit section *** (ТЧДостКон.Груз CustomAttributes)

        // *** End programmer edit section *** (ТЧДостКон.Груз CustomAttributes)
        [PropertyStorage(new string[] {
                "Груз"})]
        [NotNull()]
        public virtual IIS.Logistika_snova.Груз Груз
        {
            get
            {
                // *** Start programmer edit section *** (ТЧДостКон.Груз Get start)

                // *** End programmer edit section *** (ТЧДостКон.Груз Get start)
                IIS.Logistika_snova.Груз result = this.fГруз;
                // *** Start programmer edit section *** (ТЧДостКон.Груз Get end)

                // *** End programmer edit section *** (ТЧДостКон.Груз Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧДостКон.Груз Set start)

                // *** End programmer edit section *** (ТЧДостКон.Груз Set start)
                this.fГруз = value;
                // *** Start programmer edit section *** (ТЧДостКон.Груз Set end)

                // *** End programmer edit section *** (ТЧДостКон.Груз Set end)
            }
        }
        
        /// <summary>
        /// Т ч дост кон.
        /// </summary>
        // *** Start programmer edit section *** (ТЧДостКон.ЗагрузКонтейн CustomAttributes)

        // *** End programmer edit section *** (ТЧДостКон.ЗагрузКонтейн CustomAttributes)
        [PropertyStorage(new string[] {
                "ЗагрузКонтейн"})]
        [NotNull()]
        public virtual IIS.Logistika_snova.ЗагрузКонтейн ЗагрузКонтейн
        {
            get
            {
                // *** Start programmer edit section *** (ТЧДостКон.ЗагрузКонтейн Get start)

                // *** End programmer edit section *** (ТЧДостКон.ЗагрузКонтейн Get start)
                IIS.Logistika_snova.ЗагрузКонтейн result = this.fЗагрузКонтейн;
                // *** Start programmer edit section *** (ТЧДостКон.ЗагрузКонтейн Get end)

                // *** End programmer edit section *** (ТЧДостКон.ЗагрузКонтейн Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧДостКон.ЗагрузКонтейн Set start)

                // *** End programmer edit section *** (ТЧДостКон.ЗагрузКонтейн Set start)
                this.fЗагрузКонтейн = value;
                // *** Start programmer edit section *** (ТЧДостКон.ЗагрузКонтейн Set end)

                // *** End programmer edit section *** (ТЧДостКон.ЗагрузКонтейн Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Logistika_snova.ДокумРезультП.
        /// </summary>
        // *** Start programmer edit section *** (ТЧДостКон.ДокумРезультП CustomAttributes)

        // *** End programmer edit section *** (ТЧДостКон.ДокумРезультП CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "ДокумРезультП"})]
        public virtual IIS.Logistika_snova.ДокумРезультП ДокумРезультП
        {
            get
            {
                // *** Start programmer edit section *** (ТЧДостКон.ДокумРезультП Get start)

                // *** End programmer edit section *** (ТЧДостКон.ДокумРезультП Get start)
                IIS.Logistika_snova.ДокумРезультП result = this.fДокумРезультП;
                // *** Start programmer edit section *** (ТЧДостКон.ДокумРезультП Get end)

                // *** End programmer edit section *** (ТЧДостКон.ДокумРезультП Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧДостКон.ДокумРезультП Set start)

                // *** End programmer edit section *** (ТЧДостКон.ДокумРезультП Set start)
                this.fДокумРезультП = value;
                // *** Start programmer edit section *** (ТЧДостКон.ДокумРезультП Set end)

                // *** End programmer edit section *** (ТЧДостКон.ДокумРезультП Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТЧДостКонE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТЧДостКонE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТЧДостКонE", typeof(IIS.Logistika_snova.ТЧДостКон));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ТЧДостКон.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfТЧДостКон CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfТЧДостКон CustomAttributes)
    public class DetailArrayOfТЧДостКон : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Logistika_snova.DetailArrayOfТЧДостКон members)

        // *** End programmer edit section *** (IIS.Logistika_snova.DetailArrayOfТЧДостКон members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ТЧДостКон by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ТЧДостКон.
        /// </summary>
        public DetailArrayOfТЧДостКон(IIS.Logistika_snova.ДокумРезультП fДокумРезультП) : 
                base(typeof(ТЧДостКон), ((ICSSoft.STORMNET.DataObject)(fДокумРезультП)))
        {
        }
        
        public IIS.Logistika_snova.ТЧДостКон this[int index]
        {
            get
            {
                return ((IIS.Logistika_snova.ТЧДостКон)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Logistika_snova.ТЧДостКон dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
