//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Logistika_snova
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Т ч инф о зак.
    /// </summary>
    // *** Start programmer edit section *** (ТЧИнфОЗак CustomAttributes)

    // *** End programmer edit section *** (ТЧИнфОЗак CustomAttributes)
    [AutoAltered()]
    [Caption("Информация о заказе")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТЧИнфОЗакE", new string[] {
            "Груз as \'Код груза\'",
            "Груз.КодГруза as \'Код груза\'",
            "Груз.КатегорияГр as \'Категория груза\'",
            "Груз.Масса as \'Масса груза\'",
            "Груз.Объем as \'Объем груза\'",
            "Количество as \'Количество груза\'"}, Hidden=new string[] {
            "Груз.КодГруза"})]
    [MasterViewDefineAttribute("ТЧИнфОЗакE", "Груз", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "КодГруза")]
    public class ТЧИнфОЗак : ICSSoft.STORMNET.DataObject
    {
        
        private int fКоличество;
        
        private IIS.Logistika_snova.Груз fГруз;
        
        private IIS.Logistika_snova.ДокумПостав fДокумПостав;
        
        // *** Start programmer edit section *** (ТЧИнфОЗак CustomMembers)

        // *** End programmer edit section *** (ТЧИнфОЗак CustomMembers)

        
        /// <summary>
        /// Количество.
        /// </summary>
        // *** Start programmer edit section *** (ТЧИнфОЗак.Количество CustomAttributes)

        // *** End programmer edit section *** (ТЧИнфОЗак.Количество CustomAttributes)
        public virtual int Количество
        {
            get
            {
                // *** Start programmer edit section *** (ТЧИнфОЗак.Количество Get start)

                // *** End programmer edit section *** (ТЧИнфОЗак.Количество Get start)
                int result = this.fКоличество;
                // *** Start programmer edit section *** (ТЧИнфОЗак.Количество Get end)

                // *** End programmer edit section *** (ТЧИнфОЗак.Количество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧИнфОЗак.Количество Set start)

                // *** End programmer edit section *** (ТЧИнфОЗак.Количество Set start)
                this.fКоличество = value;
                // *** Start programmer edit section *** (ТЧИнфОЗак.Количество Set end)

                // *** End programmer edit section *** (ТЧИнфОЗак.Количество Set end)
            }
        }
        
        /// <summary>
        /// Т ч инф о зак.
        /// </summary>
        // *** Start programmer edit section *** (ТЧИнфОЗак.Груз CustomAttributes)

        // *** End programmer edit section *** (ТЧИнфОЗак.Груз CustomAttributes)
        [PropertyStorage(new string[] {
                "Груз"})]
        [NotNull()]
        public virtual IIS.Logistika_snova.Груз Груз
        {
            get
            {
                // *** Start programmer edit section *** (ТЧИнфОЗак.Груз Get start)

                // *** End programmer edit section *** (ТЧИнфОЗак.Груз Get start)
                IIS.Logistika_snova.Груз result = this.fГруз;
                // *** Start programmer edit section *** (ТЧИнфОЗак.Груз Get end)

                // *** End programmer edit section *** (ТЧИнфОЗак.Груз Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧИнфОЗак.Груз Set start)

                // *** End programmer edit section *** (ТЧИнфОЗак.Груз Set start)
                this.fГруз = value;
                // *** Start programmer edit section *** (ТЧИнфОЗак.Груз Set end)

                // *** End programmer edit section *** (ТЧИнфОЗак.Груз Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Logistika_snova.ДокумПостав.
        /// </summary>
        // *** Start programmer edit section *** (ТЧИнфОЗак.ДокумПостав CustomAttributes)

        // *** End programmer edit section *** (ТЧИнфОЗак.ДокумПостав CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "ДокумПостав"})]
        public virtual IIS.Logistika_snova.ДокумПостав ДокумПостав
        {
            get
            {
                // *** Start programmer edit section *** (ТЧИнфОЗак.ДокумПостав Get start)

                // *** End programmer edit section *** (ТЧИнфОЗак.ДокумПостав Get start)
                IIS.Logistika_snova.ДокумПостав result = this.fДокумПостав;
                // *** Start programmer edit section *** (ТЧИнфОЗак.ДокумПостав Get end)

                // *** End programmer edit section *** (ТЧИнфОЗак.ДокумПостав Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧИнфОЗак.ДокумПостав Set start)

                // *** End programmer edit section *** (ТЧИнфОЗак.ДокумПостав Set start)
                this.fДокумПостав = value;
                // *** Start programmer edit section *** (ТЧИнфОЗак.ДокумПостав Set end)

                // *** End programmer edit section *** (ТЧИнфОЗак.ДокумПостав Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТЧИнфОЗакE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТЧИнфОЗакE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТЧИнфОЗакE", typeof(IIS.Logistika_snova.ТЧИнфОЗак));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ТЧИнфОЗак.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfТЧИнфОЗак CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfТЧИнфОЗак CustomAttributes)
    public class DetailArrayOfТЧИнфОЗак : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Logistika_snova.DetailArrayOfТЧИнфОЗак members)

        // *** End programmer edit section *** (IIS.Logistika_snova.DetailArrayOfТЧИнфОЗак members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ТЧИнфОЗак by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ТЧИнфОЗак.
        /// </summary>
        public DetailArrayOfТЧИнфОЗак(IIS.Logistika_snova.ДокумПостав fДокумПостав) : 
                base(typeof(ТЧИнфОЗак), ((ICSSoft.STORMNET.DataObject)(fДокумПостав)))
        {
        }
        
        public IIS.Logistika_snova.ТЧИнфОЗак this[int index]
        {
            get
            {
                return ((IIS.Logistika_snova.ТЧИнфОЗак)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Logistika_snova.ТЧИнфОЗак dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
